name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
          - 22
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/checkout@v4

      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node }}-

      - name: Setup foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        run: npm install

      - name: Compile
        run: npm run compile
      - name: Run All Node.js Tests
        run: npm run test
