name: "test-smart-contracts"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.18.x"
          cache: npm

      - name: Install packages
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Run tests
        run: npm run sol-test
